#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    13pixel-phpmyadmin-80-http:
      entrypoints:
        - http-8036
      rule: HostRegexp(`^13pixel\.ddev\.site$`)
      
      service: "13pixel-phpmyadmin-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "13pixel-redirectHttps"
    13pixel-web-80-http:
      entrypoints:
        - http-8080
      rule: HostRegexp(`^13pixel\.ddev\.site$`)
      
      service: "13pixel-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "13pixel-redirectHttps"
    13pixel-web-8080-http:
      entrypoints:
        - http-
      rule: HostRegexp(`^13pixel\.ddev\.site$`)
      
      service: "13pixel-web-8080"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "13pixel-redirectHttps"
    13pixel-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^13pixel\.ddev\.site$`)
      
      service: "13pixel-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "13pixel-redirectHttps"
    13pixel-web-3000-http:
      entrypoints:
        - http-3001
      rule: HostRegexp(`^13pixel\.ddev\.site$`)
      
      service: "13pixel-web-3000"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "13pixel-redirectHttps"
    
    
    13pixel-phpmyadmin-80-https:
      entrypoints:
        - http-8037
      rule: HostRegexp(`^13pixel\.ddev\.site$`)
      
      service: "13pixel-phpmyadmin-80"
      ruleSyntax: v3
      
      tls: true
      
    
    
    
    
    13pixel-web-80-https:
      entrypoints:
        - http-8443
      rule: HostRegexp(`^13pixel\.ddev\.site$`)
      
      service: "13pixel-web-80"
      ruleSyntax: v3
      
      tls: true
      
    13pixel-web-8443-https:
      entrypoints:
        - http-
      rule: HostRegexp(`^13pixel\.ddev\.site$`)
      
      service: "13pixel-web-8443"
      ruleSyntax: v3
      
      tls: true
      
    13pixel-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^13pixel\.ddev\.site$`)
      
      service: "13pixel-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    13pixel-web-3000-https:
      entrypoints:
        - http-3000
      rule: HostRegexp(`^13pixel\.ddev\.site$`)
      
      service: "13pixel-web-3000"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    13pixel-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    13pixel-phpmyadmin-80:
      loadbalancer:
        servers:
          - url: http://ddev-13pixel-phpmyadmin:80
        
    
    13pixel-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-13pixel-web:80
        
    13pixel-web-8080:
      loadbalancer:
        servers:
          - url: http://ddev-13pixel-web:8080
        
    13pixel-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-13pixel-web:8025
        
    13pixel-web-3000:
      loadbalancer:
        servers:
          - url: http://ddev-13pixel-web:3000
        
    
    13pixel-web-8443:
      loadbalancer:
        servers:
          - url: http://ddev-13pixel-web:8443
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/13pixel.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/13pixel.key