color: null
fieldLayouts:
  7b6a8424-24d3-4409-872d-4a67a56d805d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-11T12:36:20+00:00'
            elementCondition: null
            fieldUid: 4060ca93-4d55-48ba-be72-11fd85105282 # Assets - Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f824a831-9ca3-443f-8c64-3d4adc49373b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 13443846-5f6e-4b81-a26c-ab7c67db028f
        userCondition: null
handle: infoSlide
hasTitleField: false
icon: circle-info
name: 'Info Slide'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
