color: green
fieldLayouts:
  004004a3-fe7f-4720-9b52-6c86a93d7dad:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-17T06:53:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1d2567ca-fa2c-46f6-97b2-89c6bf18d0b8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-17T06:52:42+00:00'
            elementCondition: null
            fieldUid: 32972c85-b85e-45de-a6a1-d58a643d3e81 # Headiing
            handle: portfolioHeading
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9883af6a-6f68-4280-8613-f8984519d09a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-12T06:26:25+00:00'
            elementCondition: null
            fieldUid: 66a07778-fa3a-4811-a67f-c5a0cf9e526c # Portfolio Tag
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 087c18e8-8e7b-4bd9-b38e-d68aceeafb6b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-12T06:21:10+00:00'
            elementCondition: null
            fieldUid: 96b2b9d7-9fe0-49ff-9a77-cd2068d2839e # Portfolio Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cde710f7-170d-47e6-9551-3d5a9276b86a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-12T06:21:10+00:00'
            elementCondition: null
            fieldUid: b77958a3-700a-4ea9-a7f4-1328358556fd # Portfolio Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8a70ca9-3b0d-4a95-98cd-db59f4f8b32c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-12T06:21:10+00:00'
            elementCondition: null
            fieldUid: 4060ca93-4d55-48ba-be72-11fd85105282 # Assets - Image
            handle: portfolioImage
            includeInCards: false
            instructions: null
            label: 'Portfolio Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 140952e8-34f7-4b29-9142-39c2062ad2fa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-12T06:21:10+00:00'
            elementCondition: null
            fieldUid: 379979f8-8b8a-4d0e-be50-cf55272ecf6c # Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae862c82-949f-4c32-aafb-e080e3f6f556
            userCondition: null
            warning: null
            width: 100
        name: 'General + Hero'
        uid: 2931103e-a97c-4528-a701-b7bedeb61a7d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-12T06:21:10+00:00'
            elementCondition: null
            fieldUid: f961ae4f-abe8-4842-b296-16d412036c48 # Content Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4cbf975d-f638-49f8-9977-bd9c3c2cb6ab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 87c19965-c0b6-4e4c-948e-9a07cd68b0e0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-12T06:21:10+00:00'
            elementCondition: null
            fieldUid: 787967f0-9a61-4502-9ec1-b413d02b9279 # Meta & Social Data
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bdf1d47-353f-4d53-8518-6bed6639e5cd
            userCondition: null
            warning: null
            width: 100
        name: 'Meta & Social Data'
        uid: 4964fb46-bf97-48f4-bf7f-6f117e90f548
        userCondition: null
handle: portfolio
hasTitleField: true
icon: address-card
name: Portfolio
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
