color: yellow
fieldLayouts:
  458f8106-08e8-43c0-b26a-815ad4c03b88:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-11T15:03:41+00:00'
            elementCondition: null
            fieldUid: 32972c85-b85e-45de-a6a1-d58a643d3e81 # Headiing
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7c3e1b5-d50f-46f2-9e39-3093188927f5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-11T15:08:00+00:00'
            elementCondition: null
            fieldUid: 86b0adf0-5bb4-4cc3-b597-b32bd746081e # Rich Text - Full
            handle: faqdescription
            includeInCards: false
            instructions: null
            label: 'FAQ Description'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 115e2aeb-5776-44d7-a5d8-501322dfadb1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-11T15:08:00+00:00'
            elementCondition: null
            fieldUid: 3ae65c29-e9b0-4b1c-a365-d56e5b103f40 # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08529107-56e0-4763-90ee-aac288c1d0fe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-11T15:03:41+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 9ee43636-ff54-451a-a04f-d026e2be4d03
            userCondition: null
          -
            dateAdded: '2025-02-11T15:03:41+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Leave FAQ content blank to display FAQ content set in **Globals**'
            type: craft\fieldlayoutelements\Tip
            uid: 098ae64f-049e-482f-9527-ef592f59bb08
            userCondition: null
          -
            dateAdded: '2025-02-11T15:03:41+00:00'
            elementCondition: null
            fieldUid: 4ba88fea-0529-4641-8cb3-08d825a4faf1 # FAQ Entries
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b252f634-361c-4757-9cb3-705b9bb4475d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1889d859-bab4-4832-9c0c-e13587952c14
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-11T15:03:41+00:00'
            elementCondition: null
            fieldUid: b8cf975c-8b0e-4f79-968b-ae246d2f8bf1 # Padding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1af32e9-6793-49ad-b56f-25a601b6ea0b
            userCondition: null
            warning: null
            width: 100
        name: 'Block Settings'
        uid: d08b27da-3855-4306-8466-86316421ae9b
        userCondition: null
handle: textFaq
hasTitleField: false
icon: question
name: 'Text + FAQ'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
