altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  4aa36c75-b9d0-4bf2-9bc2-528f8395fb64:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-06T05:09:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d1394f08-d61d-4172-a4aa-70c07161d002
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 523d27dd-3b9f-438d-be4c-dc23bad2bcb5
        userCondition: null
fs: files
handle: files
name: Files
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
