altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  e8448ad8-dd84-44c2-ac24-71caec496078:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-06T05:09:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: fa3ee532-245e-4746-b8a1-4f6933eb66a3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3a6e1ca8-a486-4407-be13-84db609c39c2
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
