defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 4042cf96-2c15-4dee-9164-d02e70bbc45d #  Fleet Detail
handle: fleet
maxAuthors: 1
name: Fleet
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: fleet/_entry
    uriFormat: 'fleet/{slug}'
structure:
  maxLevels: null
  uid: d36617ec-2cdc-4bdf-bd91-f3ecce699803
type: structure
