defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 78a09d8b-4266-4390-8f44-79f22ecfea14 # Globals
handle: globals
maxAuthors: 1
name: Globals
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
