defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 606493ad-852d-40f2-97d3-97e1cd51099f # Portfolio
handle: portfolio
maxAuthors: 1
name: Portfolio
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _pages/types/pageBlocks.twig
    uriFormat: 'portfolio/{slug}'
structure:
  maxLevels: null
  uid: 0e557d54-332d-4243-81a8-3071d04f8525
type: structure
