defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: d67ffd7a-0f91-474d-99e3-9f9ec85fbe16 # Service
handle: services
maxAuthors: 1
name: Services
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _pages/types/pageBlocks.twig
    uriFormat: 'services/{slug}'
structure:
  maxLevels: null
  uid: 856983cf-3f9b-4834-94f3-2c1784568f53
type: structure
