handle: customLight
name: 'Custom Light'
outputCssLayout: true
outputCssLocation: page-header
outputCssTheme: true
outputJsBase: true
outputJsLocation: page-footer
outputJsTheme: true
sortOrder: null
template: _forms/_form-custom-light
useCustomTemplates: true
